### ISSUE TITLE
Homepage link points to a unrelated page

### ISSUE THREAD

**Issue by alexandru-calinoiu** [ioquatix/teapot#3]
The homepage link is not relevant for this project.

**Comment by ioquatix** [comment]
Thanks, fixed.

**Comment by ioquatix** [comment]
So, I used to have kyusu.org but I didn't want it any more.. look like it's been taken over by some chinese pornography site sorry :D

**Comment by ioquatix** [comment]
BTW, what's your interest in this project? This is a crazy project! I can't imagine many people without some specific thing going on would be interested.

**Comment by alexandru-calinoiu** [comment]
I arrived to your profile from celluloid and I was browsing your repos. No specific interest in this project.

**Comment by ioquatix** [comment]
Okay well thanks dude I appreciate fixing the link since it was pretty inappropriate :D
